version: '2'

services:
  app:
    image: 'wmsfernando/reqlicit-api:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8084:8084"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/reqlicit_db
      - SPRING_DATASOURCE_USERNAME=reqlicit_admin
      - SPRING_DATASOURCE_PASSWORD=Password12
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=reqlicit_db
      - POSTGRES_USER=reqlicit_admin
      - POSTGRES_PASSWORD=Password12
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
